config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'books/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  
  # validates :image, presence: true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
  
  def create
   @books = Book.all
    
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."

       redirect_to book_path(@book)
    else
      flash.now[:error] = @book.errors.full_messages
      render :index
    end
      
  end
 
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    
  end
  
   def update
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
       redirect_to book_path(@book)
    else
      flash.now[:error] = @book.errors.full_messages
      render :edit
    end
   end
   
   def destroy
    book = Book.find(params[:id])
  	book.destroy
  	flash[:notice] = "successfully"
  	redirect_to books_path
   end
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController <  ApplicationController
  
  def top
  
  end
  
  def new
    @list = List.new
  end
  
  def create
    list = List.new(list_params)
    list.save
    redirect_to'/lists'
    
  end
 
  def index
    @list = List.all
  end

  def show
  end

  def edit
   @list = List.find(params[:id])
  end
  
  private
  def list_params
    params.require(:list).permit(:title,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1><strong>Editing Book</strong></h1>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>


<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<p><%= f.submit 'Update Book' %></p>
<% end %>

<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>



<%= link_to "Show", book_path(@book) %>
|
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h1><storong>Books</storong></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book) %></td>
      <td><%= link_to "Edit", edit_book_path(book) %></td>
     <td><%= link_to "Destroy", destroy_book_path(book), method: :delete, data: { confirm: "Are you sure?" }  %></td>

    </tr>
  <% end %>
  </thead>
</table>



<h1><strong>New book</strong></h1>
<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<%= form_with model: @book, local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

 <p><%= f.submit 'Create Book' %></p>
<% end %>

app/views/books/new.html.erb
<h4>Book was successfully created.</h4>


<h4>Title:</h4>
<%= f.text_field :title %>

<h4>Body:</h4>
<%= f.text_area :body %>

<%= link_to "Edit", edit_book_path(@book) %>
|
<%= link_to "Back", books_path %>

app/views/books/show.html.erb
<p class="notice"><%= flash[:notice] %></p>


<h4><storong>Title:<%= @book.title %></storong></h4>


<h4><strong>Body:<%= @book.body %></strong></h4>



<%= link_to "Edit", edit_book_path(@book) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>
<p><strong>Bookers</strong>では、様々な書籍に関するあなたの意見や</p>
<p>印象を共有し交換する事ができます</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>